
env:
  browser: true
  es2021: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:{
  'indent':'off',
  'react/jsx-indent':'off',
  import/extensions:
    - error
    # - ignorePackages
    - js: always
  no-console: 0