
env:
  browser: true
  es2021: true
extends:
   airbnb-base
   prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  import/extensions:
    - error
    # - ignorePackages
    - js: always
  no-console: 0
rules: {
  'no-console': 0
  'indent': 0
}