
env:
  browser: true
  es2021: true
extends:
   airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  import/extensions: 0
  no-console: 0
rules:
  no-console: 0
  import/extensions:
    - error
    - js: ignorePackages
	